// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)

import SurveysIndexController from "./surveys/index_controller"
application.register("surveys--index", SurveysIndexController)
