max_warnings: 50
verbose: false
git:
  master: main
runners: [rubocop, slimlint, scss]
#rubocop:
  # Map of RuboCop severity level to Pronto severity level
#  severities:
#    refactor: info
#    warning: error

  # Enable suggestions
#  suggestions: true
