default: &default
  adapter: postgresql
  host: postgres
  port: 5432
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: survey_spark_development

test:
  <<: *default
  database: survey_spark_test

staging:
  <<: *default
  database: survey_spark_staging

production:
  <<: *default
  database: survey_spark_production
